(ns avclj.av-error
  ;;Autogenerated from avclj.av-error-defs-- DO NOT EDIT
  ""
  (:require [avclj.av-error-defs]))

(def ^{:tag 'long} AVERROR_BSF_NOT_FOUND avclj.av-error-defs/AVERROR_BSF_NOT_FOUND)
(def ^{:tag 'long} AVERROR_BUFFER_TOO_SMALL avclj.av-error-defs/AVERROR_BUFFER_TOO_SMALL)
(def ^{:tag 'long} AVERROR_BUG avclj.av-error-defs/AVERROR_BUG)
(def ^{:tag 'long} AVERROR_BUG2 avclj.av-error-defs/AVERROR_BUG2)
(def ^{:tag 'long} AVERROR_DECODER_NOT_FOUND avclj.av-error-defs/AVERROR_DECODER_NOT_FOUND)
(def ^{:tag 'long} AVERROR_DEMUXER_NOT_FOUND avclj.av-error-defs/AVERROR_DEMUXER_NOT_FOUND)
(def ^{:tag 'long} AVERROR_EAGAIN avclj.av-error-defs/AVERROR_EAGAIN)
(def ^{:tag 'long} AVERROR_EAGAIN_MAC avclj.av-error-defs/AVERROR_EAGAIN_MAC)
(def ^{:tag 'long} AVERROR_ENCODER_NOT_FOUND avclj.av-error-defs/AVERROR_ENCODER_NOT_FOUND)
(def ^{:tag 'long} AVERROR_EOF avclj.av-error-defs/AVERROR_EOF)
(def ^{:tag 'long} AVERROR_EXIT avclj.av-error-defs/AVERROR_EXIT)
(def ^{:tag 'long} AVERROR_EXPERIMENTAL avclj.av-error-defs/AVERROR_EXPERIMENTAL)
(def ^{:tag 'long} AVERROR_EXTERNAL avclj.av-error-defs/AVERROR_EXTERNAL)
(def ^{:tag 'long} AVERROR_FILTER_NOT_FOUND avclj.av-error-defs/AVERROR_FILTER_NOT_FOUND)
(def ^{:tag 'long} AVERROR_HTTP_BAD_REQUEST avclj.av-error-defs/AVERROR_HTTP_BAD_REQUEST)
(def ^{:tag 'long} AVERROR_HTTP_FORBIDDEN avclj.av-error-defs/AVERROR_HTTP_FORBIDDEN)
(def ^{:tag 'long} AVERROR_HTTP_NOT_FOUND avclj.av-error-defs/AVERROR_HTTP_NOT_FOUND)
(def ^{:tag 'long} AVERROR_HTTP_OTHER_4XX avclj.av-error-defs/AVERROR_HTTP_OTHER_4XX)
(def ^{:tag 'long} AVERROR_HTTP_SERVER_ERROR avclj.av-error-defs/AVERROR_HTTP_SERVER_ERROR)
(def ^{:tag 'long} AVERROR_HTTP_UNAUTHORIZED avclj.av-error-defs/AVERROR_HTTP_UNAUTHORIZED)
(def ^{:tag 'long} AVERROR_INPUT_CHANGED avclj.av-error-defs/AVERROR_INPUT_CHANGED)
(def ^{:tag 'long} AVERROR_INVALIDDATA avclj.av-error-defs/AVERROR_INVALIDDATA)
(def ^{:tag 'long} AVERROR_MUXER_NOT_FOUND avclj.av-error-defs/AVERROR_MUXER_NOT_FOUND)
(def ^{:tag 'long} AVERROR_OPTION_NOT_FOUND avclj.av-error-defs/AVERROR_OPTION_NOT_FOUND)
(def ^{:tag 'long} AVERROR_OUTPUT_CHANGED avclj.av-error-defs/AVERROR_OUTPUT_CHANGED)
(def ^{:tag 'long} AVERROR_PATCHWELCOME avclj.av-error-defs/AVERROR_PATCHWELCOME)
(def ^{:tag 'long} AVERROR_PROTOCOL_NOT_FOUND avclj.av-error-defs/AVERROR_PROTOCOL_NOT_FOUND)
(def ^{:tag 'long} AVERROR_STREAM_NOT_FOUND avclj.av-error-defs/AVERROR_STREAM_NOT_FOUND)
(def ^{:tag 'long} AVERROR_UNKNOWN avclj.av-error-defs/AVERROR_UNKNOWN)
(defmacro define-error-constants
  ([error-constants]
  `(avclj.av-error-defs/define-error-constants ~error-constants)))


(def error->value-map avclj.av-error-defs/error->value-map)
(defn error-name->value
  (^{:tag long} [err-name]
  (avclj.av-error-defs/error-name->value err-name)))


(defn error-value->name
  ([err-val]
  (avclj.av-error-defs/error-value->name err-val)))


(def value->error-map avclj.av-error-defs/value->error-map)
