#!/bin/bash

set -e

rm -rf classes && mkdir classes
clojure -X:depstar

pushd library

$GRAALVM_HOME/bin/native-image \
    --report-unsupported-elements-at-runtime \
    --initialize-at-build-time \
    --no-fallback \
    --no-server \
    -H:+ReportExceptionStackTraces \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    -J-Dtech.v3.datatype.graal-native=true \
    -jar ../target/avclj-uber.jar -cp classes \
    --shared -H:Name=libavclj
popd
